project:
  type: website
  output-dir: docs

website:
  title: "Sena Sivrikaya's Analytics Lab"
  navbar:
    search: true
    background: white
    foreground: "#000000"
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: Projects
        href: project.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Assignment 1
            href: assignments/assignment-1.qmd
          - text: Assignment 2
            href: assignments/assignment-2.qmd

    tools:
      - icon: github
        href: https://github.com/ssivrikaya
      - icon: linkedin
        href: https://www.linkedin.com/in/sena-sivrikaya/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd

  page-navigation: true
  back-to-top-navigation: true

  page-footer:
    center: "Hacettepe IE - EMU430 - Spring 2026"
    border: true

format:
  html:
    toc: true
    toc-location: left
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual